"""empty message

Revision ID: d4d585087960
Revises: f4037c80a748
Create Date: 2022-05-29 07:15:41.156106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4d585087960'
down_revision = 'f4037c80a748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'seeking_description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('Artist', 'created_at')
    op.alter_column('Venue', 'seeking_description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('Venue_artist_id_fkey', 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'artist_id')
    op.drop_column('Venue', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Venue_artist_id_fkey', 'Venue', 'Artist', ['artist_id'], ['id'])
    op.alter_column('Venue', 'seeking_description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('Artist', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('Artist', 'seeking_description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
